# Code Generated by Sidekick is for learning and experimentation purposes only.
from pathlib import Path

SRC_PATH = r"housemate/src/app"  # <-- adjust this path as needed   
OUTPUT_README = "README_DUMP.md"  # <-- output file name

root = Path(SRC_PATH).resolve()
out = root / OUTPUT_README

# Folders to skip (common in JS/Angular repos)
SKIP_DIRS = {".git", "node_modules", "dist", "build", ".angular", ".cache", "coverage", ".vscode", ".idea"}

def should_skip(path: Path) -> bool:
    return any(part in SKIP_DIRS for part in path.parts)

all_files = sorted(
    [p for p in root.rglob("*") if p.is_file() and not should_skip(p)],
    key=lambda p: str(p.relative_to(root)).lower(),
)

with out.open("w", encoding="utf-8") as f:
    f.write(f"# src file dump\n\nRoot: `{root}`\n\n---\n\n")

    for p in all_files:
        if p == out:
            continue

        rel = p.relative_to(root)

        # Read as text where possible; if binary-ish, still include a note
        try:
            content = p.read_text(encoding="utf-8", errors="replace")
            is_text = True
        except Exception:
            content = ""
            is_text = False

        f.write(f"## {rel.as_posix()}\n\n")
        f.write(f"- Absolute path: `{p.resolve()}`\n\n")

        if is_text:
            ext = p.suffix.lstrip(".") or "text"
            f.write(f"```{ext}\n")
            f.write(content)
            if not content.endswith("\n"):
                f.write("\n")
            f.write("```\n\n---\n\n")
        else:
            f.write("_Binary or unreadable as UTF-8 text; skipped content._\n\n---\n\n")

print(f"Created: {out}")

